-- migrate:up
-- Users own the messages they send. The id is a UUID generated by Postgres
-- (gen_random_uuid is built in on Postgres 13+). username is stored already
-- normalized to lowercase by the app, so a plain UNIQUE enforces case-insensitive
-- uniqueness. Only the bcrypt hash is stored, never the password.
CREATE TABLE users (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    username      TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- migrate:down
DROP TABLE users;
